### PR TITLE
Add french translation to the open Terminal article

### LINKED ISSUE #72: Create a French translation of the open terminal guide
Based on the English version of the guide (https://github.com/devadvance/terminalcheatsheet/blob/staging/guides/open-terminal-macos.md), create a French translation in https://github.com/devadvance/terminalcheatsheet/blob/staging/i18n/fr/guides/open-terminal-macos.md.

It is OK to use the English images/GIFs.

### PR DESCRIPTION
**Pull request by beltzawoo**
# Pull Request

## Description

Translated the whole thing to french, but I'm not sure if we should localize "cheat sheet" or if the translations for "go menu" and "utilities" are correct.

Fixes #72

## Required checklist:

* [x] My code matches the existing code style of this project.
* **One** of these:
	* [ ] My content is localized for all of the locales that this project currently supports.
	* [ ] I described above how I plan to localize this content immediately after merging these changes.
        * [x] This is localization.
* [x] I have tested my code and it successfully builds for GitHub Pages and validates as AMP.

### CODE REVIEW

**Comment by devadvance** [comment]
This looks great. If you were searching for this material, would you expect "cheat sheet" to be translated, or in English since it's more like a product name?

**Comment by beltzawoo** [comment]
If it was a big picture, the closest expression to "cheat sheet" would probably be "fiche mémo", but since it's a website and the domain name is "terminalcheatsheet.com", I think it would be better to just leave it as it is, as a product name. The literal translation of "cheat sheet" is "antisèche", but it's generally only used for cheating at school! :stuck_out_tongue:

**Comment by devadvance** [comment]
Awesome, we will keep "cheat sheet" then! Thanks for teaching me several things today 😄

**Review by devadvance — APPROVED** [review]
LGTM. Thanks for the great work and contribution!!

**Pull request merged**
