### PR TITLE
Added Bahasa (Indonesia) Translations for command descriptions

### PR DESCRIPTION
**Pull request by AjiArya**
## Description

Added Bahasa (Indonesia) Translation

Fixes # _90_

## Required checklist:

* [x] My code matches the existing code style of this project.

### CODE REVIEW

**Comment by AjiArya** [comment]
@devadvance I'm having problem with `line too long (82 > 80 characters)  (line-length)` how can I fix this?

**Comment by devadvance** [comment]
I'll fix the conflicts via the command line since it can't be done on GitHub. Will comment again in a few minutes!

**Review by devadvance — APPROVED** [review]
Looks good to me. I'm approving but am merging the changes via command line to address conflicts. Thanks for the contribution!

**Comment by devadvance** [comment]
I've merged these changes locally and pushed to `staging`. You can see them here: https://github.com/devadvance/terminalcheatsheet/commit/8dd273f7bb3cc441ab1b0dbada1acf6ec73ce8c6

I've also added the `hacktoberfest-accepted` label to this PR so that it qualifies even though the merge was performed locally. Thanks for adding these translations!

**Pull request closed without merging**
